# Generated by Django 3.2 on 2021-05-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Original_image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_image', models.BinaryField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('split_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Split_image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('split_image', models.BinaryField()),
                ('predict_value', models.CharField(max_length=20)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.original_image')),
            ],
        ),
        migrations.CreateModel(
            name='Raspberry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.farm')),
            ],
        ),
        migrations.AddField(
            model_name='original_image',
            name='raspberry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.raspberry'),
        ),
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.user'),
        ),
    ]
