# Generated by Django 3.0 on 2021-05-26 12:54

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.User')),
            ],
            options={
                'unique_together': {('id', 'user')},
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Raspberry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('farm', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.User')),
            ],
            options={
                'unique_together': {('id', 'user')},
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Original_image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_image', models.BinaryField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('split_count', models.IntegerField()),
                ('raspberry', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.Raspberry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.User')),
            ],
            options={
                'unique_together': {('id', 'user')},
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Split_image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('split_image', models.BinaryField()),
                ('predict_value', models.CharField(max_length=20)),
                ('original_image', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.Original_Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middle_server.User')),
            ],
            options={
                'unique_together': {('id', 'user')},
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]

