# Generated by Django 3.0 on 2021-05-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middle_server', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            ALTER TABLE middle_server_farm
            DROP CONSTRAINT middle_server_farm_pkey CASCADE;

            ALTER TABLE middle_server_farm
            ADD CONSTRAINT middle_server_farm_pkey
            PRIMARY KEY (user_id, id);
            """),
        migrations.RunSQL("""
            ALTER TABLE middle_server_raspberry
            DROP CONSTRAINT middle_server_raspberry_pkey CASCADE;

            ALTER TABLE middle_server_raspberry
            ADD CONSTRAINT middle_server_raspberry_pkey
            PRIMARY KEY (user_id, id);
            """),
        migrations.RunSQL("""
            ALTER TABLE middle_server_original_image
            DROP CONSTRAINT middle_server_original_image_pkey CASCADE;

            ALTER TABLE middle_server_original_image
            ADD CONSTRAINT middle_server_original_image_pkey
            PRIMARY KEY (user_id, id);
            """),
        migrations.RunSQL("""
            ALTER TABLE middle_server_split_image
            DROP CONSTRAINT middle_server_split_image_pkey CASCADE;

            ALTER TABLE middle_server_split_image
            ADD CONSTRAINT middle_server_split_image_pkey
            PRIMARY KEY (user_id, id);
            """),
    ]

