# Generated by Django 3.0 on 2021-05-26 12:57

from django.db import migrations
from django_multitenant.db import migrations as tenant_migrations

class Migration(migrations.Migration):

    dependencies = [
        ('middle_server', '0002_remove_simple_pk'),
    ]

    operations = [
        tenant_migrations.Distribute('User'),
        tenant_migrations.Distribute('Farm'),
        tenant_migrations.Distribute('Raspberry'),
        tenant_migrations.Distribute('Original_image'),
        tenant_migrations.Distribute('Split_image'),
    ]
